name: Release

on:
  push:
    branches:
      - "master"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node (latest)
        uses: actions/setup-node@v1
        with:
          node_version: 12
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Prepare Npm
        run: sh npm.sh
      - name: Test
        run: npm run testd
